/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.GenericListDTORoleRequestDTO;
import io.swagger.client.model.GenericListDTOUserRequestDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MappingRequestDTOUserRequestDTORoleRequestDTO
 */


public class MappingRequestDTOUserRequestDTORoleRequestDTO {
  @SerializedName("contentA")
  private GenericListDTOUserRequestDTO contentA = null;

  @SerializedName("contentB")
  private GenericListDTORoleRequestDTO contentB = null;

  public MappingRequestDTOUserRequestDTORoleRequestDTO contentA(GenericListDTOUserRequestDTO contentA) {
    this.contentA = contentA;
    return this;
  }

   /**
   * Get contentA
   * @return contentA
  **/
  @Schema(description = "")
  public GenericListDTOUserRequestDTO getContentA() {
    return contentA;
  }

  public void setContentA(GenericListDTOUserRequestDTO contentA) {
    this.contentA = contentA;
  }

  public MappingRequestDTOUserRequestDTORoleRequestDTO contentB(GenericListDTORoleRequestDTO contentB) {
    this.contentB = contentB;
    return this;
  }

   /**
   * Get contentB
   * @return contentB
  **/
  @Schema(description = "")
  public GenericListDTORoleRequestDTO getContentB() {
    return contentB;
  }

  public void setContentB(GenericListDTORoleRequestDTO contentB) {
    this.contentB = contentB;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MappingRequestDTOUserRequestDTORoleRequestDTO mappingRequestDTOUserRequestDTORoleRequestDTO = (MappingRequestDTOUserRequestDTORoleRequestDTO) o;
    return Objects.equals(this.contentA, mappingRequestDTOUserRequestDTORoleRequestDTO.contentA) &&
        Objects.equals(this.contentB, mappingRequestDTOUserRequestDTORoleRequestDTO.contentB);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contentA, contentB);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MappingRequestDTOUserRequestDTORoleRequestDTO {\n");
    
    sb.append("    contentA: ").append(toIndentedString(contentA)).append("\n");
    sb.append("    contentB: ").append(toIndentedString(contentB)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}