/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.GenericListDTORightResponseDTO;
import io.swagger.client.model.GenericListDTORoleResponseDTO;
import io.swagger.client.model.GenericListDTOUserResponseDTO;
import io.swagger.client.model.MappingRequestDTORoleRequestDTORightRequestDTO;
import io.swagger.client.model.MappingRequestDTOUserRequestDTORoleRequestDTO;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for MappingControllerApi
 */
@Ignore
public class MappingControllerApiTest {

    private final MappingControllerApi api = new MappingControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteRolesRightsMappingTest() throws Exception {
        MappingRequestDTORoleRequestDTORightRequestDTO body = null;
        Object response = api.deleteRolesRightsMapping(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteUsersRolesMappingTest() throws Exception {
        MappingRequestDTOUserRequestDTORoleRequestDTO body = null;
        Object response = api.deleteUsersRolesMapping(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRightsForRoleTest() throws Exception {
        Integer role = null;
        GenericListDTORightResponseDTO response = api.getRightsForRole(role);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRightsForUserTest() throws Exception {
        Integer user = null;
        GenericListDTORightResponseDTO response = api.getRightsForUser(user);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRolesForRightTest() throws Exception {
        Integer right = null;
        GenericListDTORoleResponseDTO response = api.getRolesForRight(right);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRolesForUserTest() throws Exception {
        Integer user = null;
        GenericListDTORoleResponseDTO response = api.getRolesForUser(user);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUsersForRightTest() throws Exception {
        Integer right = null;
        GenericListDTOUserResponseDTO response = api.getUsersForRight(right);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUsersForRoleTest() throws Exception {
        Integer role = null;
        GenericListDTOUserResponseDTO response = api.getUsersForRole(role);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void putRolesRightsMappingTest() throws Exception {
        MappingRequestDTORoleRequestDTORightRequestDTO body = null;
        Object response = api.putRolesRightsMapping(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void putUsersRolesMappingTest() throws Exception {
        MappingRequestDTOUserRequestDTORoleRequestDTO body = null;
        Object response = api.putUsersRolesMapping(body);

        // TODO: test validations
    }
}
