/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.GenericListDTORightResponseDTO;
import io.swagger.client.model.RightResponseDTO;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for RightControllerApi
 */
@Ignore
public class RightControllerApiTest {

    private final RightControllerApi api = new RightControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllRightsTest() throws Exception {
        GenericListDTORightResponseDTO response = api.getAllRights();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getById2Test() throws Exception {
        Integer id = null;
        RightResponseDTO response = api.getById2(id);

        // TODO: test validations
    }
}
